# Generated by Django 4.1.3 on 2022-12-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.TextField()),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='WalletDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('wallet_name', models.TextField()),
                ('wallet_password', models.TextField()),
                ('seed', models.TextField()),
                ('balance', models.FloatField()),
                ('wallet_address', models.TextField()),
            ],
        ),
    ]
