# Generated by Django 4.1.3 on 2022-12-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DenariiMobile', '0002_walletdetails_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletdetails',
            name='test',
        ),
    ]
