# Generated by Django 4.1.3 on 2022-12-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DenariiMobile', '0003_remove_walletdetails_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletdetails',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='walletdetails',
            name='seed',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='walletdetails',
            name='wallet_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='walletdetails',
            name='wallet_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='walletdetails',
            name='wallet_password',
            field=models.TextField(null=True),
        ),
    ]
