# Generated by Django 4.1.3 on 2023-07-03 15:08

from django.db import migrations, models
import uuid

from Backend.settings import *


class Migration(migrations.Migration):

    dependencies = [
        ('DenariiMobile', '0003_rename_user_denariiask_denarii_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletdetails',
            name='wallet_details_id',
            field=models.UUIDField(default=uuid.uuid5(DENARII_UUID5_NAMESPACE,
                                                      DENARII_UUID5_WALLET_DETAILS_NAME), editable=False, primary_key=True,
                                   serialize=False, null=True),
        ),
        migrations.AlterField(
            model_name='walletdetails',
            name='user_identifier',
            field=models.TextField(null=True),
        ),
    ]
