# Generated by Django 4.1.3 on 2023-07-03 15:09

from django.db import migrations, models
import uuid
from Backend.settings import *


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('DenariiMobile', 'WalletDetails')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid5(DENARII_UUID5_NAMESPACE, DENARII_UUID5_WALLET_DETAILS_NAME)
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('DenariiMobile', '0004_walletdetails_wallet_details_id_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
