# Generated by Django 4.1.3 on 2023-07-03 15:10

from django.db import migrations, models
import uuid
from Backend.settings import *


class Migration(migrations.Migration):
    dependencies = [
        ('DenariiMobile', '0005_auto_20230703_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletdetails',
            name='wallet_details_id',
            field=models.UUIDField(default=uuid.uuid5(DENARII_UUID5_NAMESPACE,
                                                      DENARII_UUID5_WALLET_DETAILS_NAME), unique=True),
        ),
    ]
