# Generated by Django 4.1.3 on 2023-07-03 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DenariiMobile', '0006_auto_20230703_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denariiask',
            name='ask_id',
            field=models.UUIDField(default=uuid.UUID('f11e2aff-6e29-553f-b12a-d267b7abee49'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='walletdetails',
            name='wallet_details_id',
            field=models.UUIDField(default=uuid.UUID('06322ef3-f662-5bd6-9f23-6a5e7bd2f720'), editable=False, primary_key=True, serialize=False),
        ),
    ]
