# Generated by Django 4.1.3 on 2023-07-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DenariiMobile', '0007_alter_denariiask_ask_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denariiask',
            name='user_identifier',
            field=models.TextField(null=True),
        ),
    ]
