# Generated by Django 4.1.3 on 2023-07-03 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DenariiMobile', '0008_denariiask_user_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletdetails',
            old_name='wallet_details_id',
            new_name='primary_key',
        ),
        migrations.AddField(
            model_name='denariiask',
            name='primary_key',
            field=models.UUIDField(default=uuid.UUID('f11e2aff-6e29-553f-b12a-d267b7abee49'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='denariiask',
            name='ask_id',
            field=models.TextField(null=True),
        ),
    ]
