# Generated by Django 4.1.3 on 2023-07-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DenariiMobile', '0011_response_remove_denariiask_user_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='credit_card_number',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='expiration_date_month',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='expiration_date_year',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='customer_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='source_token_id',
            field=models.TextField(null=True),
        ),
    ]
