# Generated by Django 4.1.3 on 2023-07-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DenariiMobile', '0012_remove_creditcard_credit_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denariiask',
            name='has_been_seen_by_seller',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='denariiask',
            name='is_settled',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='transaction_was_settled',
            field=models.BooleanField(null=True),
        ),
    ]
