# Generated by Django 4.1.3 on 2023-07-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DenariiMobile', '0013_denariiask_has_been_seen_by_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denariiuser',
            name='identity_is_verified',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='denariiuser',
            name='report_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='verification_status',
            field=models.TextField(null=True),
        ),
    ]
