# Generated by Django 4.1.3 on 2023-07-22 17:30

import DenariiMobile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DenariiMobile', '0014_denariiuser_identity_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('primary_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('support_id', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='creditcard',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='denariiask',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='denariiask',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='denariiuser',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='denariiuser',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='author',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='creation_time_body',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='updated_time_body',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletdetails',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='walletdetails',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='SupportTicketComment',
            fields=[
                ('primary_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('support_ticket', models.ForeignKey(default=DenariiMobile.models.get_default_support_ticket, on_delete=django.db.models.deletion.CASCADE, to='DenariiMobile.supportticket')),
            ],
        ),
        migrations.AddField(
            model_name='supportticket',
            name='denarii_user',
            field=models.ForeignKey(default=DenariiMobile.models.get_default_denarii_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
