# Generated by Django 4.1.3 on 2023-07-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DenariiMobile', '0015_supportticket_creditcard_creation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='support_ticket_id',
            field=models.TextField(null=True),
        ),
    ]
