# Generated by Django 4.1.3 on 2023-11-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DenariiMobile', '0016_denariiask_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='comment_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='supportticketcomment',
            name='comment_id',
            field=models.TextField(null=True),
        ),
    ]
