# Generated by Django 4.2.9 on 2024-01-10 21:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DenariiMobile', '0017_response_comment_id_supportticketcomment_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denariiuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
