# Generated by Django 4.2.9 on 2024-01-21 15:09

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DenariiMobile', '0018_alter_denariiuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletdetails',
            name='wallet_password',
            field=django_cryptography.fields.encrypt(models.TextField(null=True)),
        ),
    ]
